pub fn escape_md(text: &str) -> String {
    text.replace('\\', r"\\")
        .replace('*', r"\*")
        .replace('_', r"\_")
        .replace('`', r"\`")
        .replace('{', r"\{")
        .replace('}', r"\}")
        .replace('[', r"\[")
        .replace(']', r"\]")
        .replace('(', r"\(")
        .replace(')', r"\)")
        .replace('#', r"\#")
        .replace('+', r"\+")
        .replace('-', r"\-")
        .replace('.', r"\.")
        .replace('!', r"\!")
        .replace('|', r"\|")
        .to_string()
}

pub fn unescape_md(text: &str) -> String {
    text.replace(r"\*", "*")
        .replace(r"\_", "_")
        .replace(r"\`", "`")
        .replace(r"\{", "{")
        .replace(r"\}", "}")
        .replace(r"\[", "[")
        .replace(r"\]", "]")
        .replace(r"\(", "(")
        .replace(r"\)", ")")
        .replace(r"\#", "#")
        .replace(r"\+", "+")
        .replace(r"\-", "-")
        .replace(r"\.", ".")
        .replace(r"\!", "!")
        .replace(r"\|", "|")
        .replace(r"\\", "\\")
        .to_string()
}
