name: Main

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          components: rustfmt, clippy
          profile: minimal
          override: true

      # selecting a toolchain should happen before the plugin, as the cache uses the current rustc version as its cache key
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install clippy
        run: rustup component add clippy

      - name: Just CLI
        uses: extractions/setup-just@v1
        with:
          just-version: '1.4.0'
          # Uncomment and set MY_GITHUB_TOKEN secret in repository settings to enable github authentication
          # for just installation https://github.com/extractions/setup-just?tab=readme-ov-file#usage
          # github-token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Format
        run: just fmt

      - name: Clippy
        run: just clippy

      # TODO add tests
      # - name: Test
      #   run: just test

      - name: Audit dependencies
        run: |
          cargo install --locked cargo-audit
          just audit
      